### ISSUE TITLE
Doesn't work with HF24 RPC node

### ISSUE THREAD

**Issue by Jolly-Pirate** [netuoso/vessel#8]
Vessel doesn't work with a 1.24.x RPC, when I set the node, vessel becomes a blank page, there's no way I can set to another RPC afterwards.

**Comment by 4Ykw** [comment]
Same here.

**Comment by Jolly-Pirate** [comment]
Fixed in https://github.com/netuoso/vessel/releases/tag/v0.5.0

**Comment by 4Ykw** [comment]
Thanks!
